from tkinter import *
import calendar
def submit(event):
    cal=val.get()
    cal=int(cal)
    result=calendar.calendar(cal)
    root1=Tk()
    t=Text(root1,height=150,width=80)
    t.pack()
    t.insert(END,result)
    root1.mainloop()
def click(event):
    root.destroy()
root=Tk()
root.geometry("400x400")
root.title("calender")
val=StringVar()
val.set("")
l1=Label(root,text="CALENDER",fg="black",bg="yellow",font="lucida 35 bold")
l1.pack()
l2=Label(root,text="enter year",fg="black",bg="red",font="lucida 20 bold")
l2.pack()
e=Entry(root,textvariable=val)
e.pack()
b1=Button(root,text="Submit",fg="black",bg="red",font="lucida 10 bold")
b1.pack()
b1.bind("<Button>",submit)
b2=Button(root,text="exit",fg="black",bg="red",font="lucida 10 bold")
b2.pack()
b2.bind("<Button>",click)
root.mainloop()